version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    # Allow maintainers to configure reviewers or labels on Dependabot PRs in repo settings
