kind = "web"
previewPath = "/"
title = "Soroban VRF"
version = "1.0.0"
id = "artifacts/soroban-vrf"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25790

[services.development]
run = "pnpm --filter @workspace/soroban-vrf run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/soroban-vrf", "run", "build" ]
publicDir = "artifacts/soroban-vrf/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25790"
BASE_PATH = "/"
