uploads = []
generated = []

[[outputs]]
id = "5hN3okp7uIuTtMzRKtdKA"
uri = "file://README.md"
type = "text"
title = "README.md"

[[outputs]]
id = "RQNDUcx1dAfBWMjiznKNZ"
uri = "file://TECH_ARCH.md"
type = "text"
title = "TECH_ARCH.md — Technical Architecture"
